# --- base CI configuration ---

image: $CI_REGISTRY/qqvp/containers/qqvp-dev:latest

variables:
  FF_SCRIPT_SECTIONS: True
  GIT_DEPTH: 10
  GIT_FETCH_EXTRA_FLAGS: --filter=blob:none --filter=tree:0 --prune --quiet
  AUTHENTICATED_GIT_URL: "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}"
  GIT_SUBMODULE_STRATEGY: recursive
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/generic/qqvp_release"
  CTEST_OUTPUT_ON_FAILURE: "ON"
  RESULTS_DIR: "${CI_PROJECT_DIR}/${CI_PIPELINE_ID}_ci_results"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_COMMIT_TAG

# This job will only run on MRs. Jobs that extend .mr-job must override the
# script section, but not before_script. The script can make use of $SOURCE_REF
# and $TARGET_REF.
#
# Note: we try set-url first when configuring the source repo because gitlab
# runners will preserve the repo configs in between builds, so `remote add`
# might fail on the second run.
#
.mr-job:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - GITLAB_URL="$(echo "$CI_SERVER_URL" | sed -e 's/^.*:\/\///g' -e 's/:[0-9]*$//g')"
    - TARGET_REPO="https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_URL}/${CI_MERGE_REQUEST_PROJECT_PATH}.git"
    - git remote set-url target_repo "$TARGET_REPO" >/dev/null 2>&1 ||
      git remote add target_repo "$TARGET_REPO"
    - git fetch target_repo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - TARGET_REF="$(git rev-parse FETCH_HEAD)"
    - SOURCE_REF="$(git rev-parse HEAD)"
    - if test -z "$TARGET_REF" || test -z "$SOURCE_REF"; then
        echo 'failed to set MR refs';
        exit 1;
      fi
    - echo "TARGET_REF is $(git show --quiet --pretty=reference $TARGET_REF)"
    - echo "SOURCE_REF is $(git show --quiet --pretty=reference $SOURCE_REF)"
  script:
    - echo "jobs extending .mr-job must override the script section"
    - exit 1

# Jobs wanting to trigger downstream pipelines must extend this template
# and set OVERRIDE_PKG to the name of the package to override.
#
.base-trigger:
  trigger:
    strategy: depend
  allow_failure: true
  inherit:
    variables: false
  variables:
    OVERRIDE_REF: $CI_COMMIT_REF_NAME
    OVERRIDE_PATH: $CI_PROJECT_PATH
    OVERRIDE_MR_PATH: $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH
  # Avoid nested pipeline triggering (e.g. libqemu -> qbox -> qqvp)
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: manual

# --- build/test pipeline ---

stages:
  - pages
  - build
  - test
  - upload
  - release
  - cleanup

.general_build_job_template:
  image: $IMAGE
  stage: test
  script:
    - |
      if test -n "$SDKROOT_SET_CMD"; then
        SDKROOT=$($SDKROOT_SET_CMD)
        export SDKROOT
      fi
    - mkdir -p build ${RESULTS_DIR}
    - OVERRIDE_URL="${OVERRIDE_URL:-${CI_SERVER_HOST}/${OVERRIDE_MR_PATH:-$OVERRIDE_PATH}.git}"
    - echo "OVERRIDE_PKG = $OVERRIDE_PKG";
      echo "OVERRIDE_REF = $OVERRIDE_REF";
      echo "OVERRIDE_URL = $OVERRIDE_URL"
    - |
      if test -n "$OVERRIDE_PKG" && test -n "$OVERRIDE_REF" && test -n "$OVERRIDE_URL"; then
        git clone --depth=1 "https://gitlab-ci-token:${CI_JOB_TOKEN}@${OVERRIDE_URL}" --branch $OVERRIDE_REF override_repo
        override_args="-DCPM_${OVERRIDE_PKG}_SOURCE=$PWD/override_repo"
      fi
    - echo cmake -B build -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=./${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA} -DCPM_DOWNLOAD_ALL=1
      ${STEP_CMAKE_ARGS} ${REPO_CMAKE_ARGS} ${override_args} ;
      cmake -B build -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=./${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA} -DCPM_DOWNLOAD_ALL=1
      ${STEP_CMAKE_ARGS} ${REPO_CMAKE_ARGS} ${override_args}
      2>&1 | tee ${RESULTS_DIR}/cmake.log
    - make -C build -j      2>&1 | tee ${RESULTS_DIR}/make.log
    - make -C build install 2>&1 | tee ${RESULTS_DIR}/install.log
    - tar --exclude-vcs -zcf $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.tar.gz $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA
    - if test "$EXECUTE_TESTS" -ne 0;
      then
        make -C build test ARGS='--output-junit test_run.xml' 2>&1 | tee ${RESULTS_DIR}/test_run.log;
        mv build/test_run.xml ${RESULTS_DIR};
      fi
  artifacts:
    when: always
    expire_in: 4 days
    paths:
      - ${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}.tar.gz
      - ${RESULTS_DIR}
    reports:
      junit: ${RESULTS_DIR}/test_run.xml

check_format:
  extends: .mr-job
  stage: test
  script:
    - git clang-format --diff --verbose --extensions 'cc,cpp,h,c' $TARGET_REF $SOURCE_REF | tee clang-format.out
    - if grep -q -F 'diff --git' clang-format.out; then exit 1; fi
  allow_failure: true

.build_src_tarball:
  stage: build
  script:
    - mkdir Packages
    - (set -x;
      cmake -Bbuild -DCPM_SOURCE_CACHE=Packages -DGREENSOCS_GIT=${CI_SERVER_URL}/qqvp/ -DGS_ONLY=${LOCAL_DEPS_ONLY} )
    - rm -rf build
    - /bin/sh ./scripts/tar_builder.sh $CI_PROJECT_DIR
    - cd ..
    - tar --exclude-vcs -zcf ${CI_PROJECT_NAME}${TARBALL_SUFFIX}.tgz $CI_PROJECT_NAME
    - mv ${CI_PROJECT_NAME}${TARBALL_SUFFIX}.tgz $CI_PROJECT_NAME/
  artifacts:
    paths:
      - ${CI_PROJECT_NAME}${TARBALL_SUFFIX}.tgz

src_tarball_locals:
  extends: .build_src_tarball
  variables:
    LOCAL_DEPS_ONLY: "True"
    TARBALL_SUFFIX: "_local"
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "schedule"

src_tarball_all:
  extends: .build_src_tarball
  variables:
    LOCAL_DEPS_ONLY: "False"
    TARBALL_SUFFIX: "_all"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

upload:
  stage: upload
  variables:
    TARBALL_SUFFIX: "_local"
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - TAG_VERSION=$(echo ${CI_COMMIT_TAG} | sed 's/^v//')
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $CI_PROJECT_DIR/${CI_PROJECT_NAME}${TARBALL_SUFFIX}.tgz "${PACKAGE_REGISTRY_URL}/${TAG_VERSION}/${CI_PROJECT_NAME}${TARBALL_SUFFIX}.tgz"'
    - |
      if test -f "${CI_PROJECT_DIR}/docs/qqvp/RELEASE-NOTES.txt"
      then
        curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${CI_PROJECT_DIR}/docs/qqvp/RELEASE-NOTES.txt" "${PACKAGE_REGISTRY_URL}/${TAG_VERSION}/RELEASE-NOTES.txt"
      fi
  dependencies:
    - src_tarball_locals
  when: always

release:
  stage: release
  variables:
    TARBALL_SUFFIX: "_local"
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - curl --location --output /usr/local/bin/release-cli "https://gitlab.com/api/v4/projects/gitlab-org%2Frelease-cli/packages/generic/release-cli/latest/release-cli-linux-amd64"
    - chmod +x /usr/local/bin/release-cli
    - TAG_VERSION=$(echo ${CI_COMMIT_TAG} | sed 's/^v//')
    - release-cli create --name "Release $CI_COMMIT_TAG" --description "Release $TAG_NAME, see the RELEASE-NOTES.txt attached for more details." --tag-name "$CI_COMMIT_TAG" --assets-link "{\"url\":\"${PACKAGE_REGISTRY_URL}/${TAG_VERSION}/${CI_PROJECT_NAME}${TARBALL_SUFFIX}.tgz\",\"name\":\"${CI_PROJECT_NAME}${TARBALL_SUFFIX}.tgz\"}" --assets-link "{\"url\":\"${PACKAGE_REGISTRY_URL}/${TAG_VERSION}/RELEASE-NOTES.txt\",\"name\":\"RELEASE-NOTES.txt\"}"
  dependencies:
    - upload
  when: always

pages:
  stage: pages
  script:
  - doxygen -g
  - sed -i "s#PROJECT_NAME *= *\".*\"#PROJECT_NAME = ${CI_PROJECT_NAME}#" Doxyfile
  - sed -i "s#RECURSIVE *= *NO#RECURSIVE = YES#" Doxyfile
  - |
      if test -f "${CI_PROJECT_DIR}/docs/qqvp/qqvp_user_doc.md"
      then
        echo "Adding qqvp_user_doc.md"
        sed -i "s#INPUT *= *#INPUT = ./ ./docs/qqvp/qqvp_user_doc.md#" Doxyfile
      fi
  - sed -i "s#HTML_OUTPUT *= .*#HTML_OUTPUT = public#" Doxyfile
  - sed -i "s#GENERATE_LATEX *= *YES#GENERATE_LATEX = NO#" Doxyfile
  - sed -i "s#EXCLUDE *= *#EXCLUDE = tests/ build/ docs/ scripts/ configs/#" Doxyfile
  - doxygen Doxyfile
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# --- from qbox .gitlab-ci.yml ---

repolinter:
  stage: build
  tags:
    - linux
  script:
    - echo "start repolinter for Qbox"
    - repolinter lint ../Qbox

.build_job_template:
  needs: ["repolinter"]
  extends:
    - .general_build_job_template
  variables:
    REPO_CMAKE_ARGS: -DLIBQEMU_TARGETS='aarch64;hexagon;xtensa;riscv64;riscv32'
    IMAGE: $CI_REGISTRY/qqvp/containers/qqvp-dev-u22:latest
    EXECUTE_TESTS: 1

qqvp-trigger:
  extends: .base-trigger
  trigger:
    project: qqvp/qqvp
  variables:
    OVERRIDE_PKG: qbox
    IMAGE: $CI_REGISTRY/qqvp/containers/qqvp-dev-u22:latest

build_make:
  extends: .build_job_template

build_lto:
  extends: .build_job_template
  variables:
    STEP_CMAKE_ARGS: -DGS_ENABLE_LLD=ON -DGS_ENABLE_LTO=ON -DCMAKE_TOOLCHAIN_FILE=./cmake/clang-toolchain.cmake
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: manual
      allow_failure: true

build_check_cxx_libcxx:
  extends: .build_job_template
  variables:
    MALLOC_CHECK_: 3
    STEP_CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=./cmake/clang-toolchain.cmake
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: manual
      allow_failure: true

build_macos:
  tags:
   - mac
  extends: .build_job_template
  variables:
    SDKROOT_SET_CMD: xcrun --sdk macosx --show-sdk-path
    GIT_STRATEGY: clone

build_ubuntu22:
  extends: .build_job_template
  image: $CI_REGISTRY/qqvp/containers/qqvp-dev-u22:latest
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "schedule"

# Save space on space-restricted runners
clean:
  tags:
    - mac
  variables:
    GIT_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  dependencies: []
  stage: cleanup
  script:
    - echo "[cleanup] removing $CI_PROJECT_DIR"
  after_script:
    - rm -rf $CI_PROJECT_DIR
  rules:
    - when: always
