-- This file is automatically generated by `cargo xtask lua`.
-- It is not intended for manual editing.
_bootloader_aarch64 = {
    -- <.start>:
    0xd53800a6, -- 	mrs	x6, mpidr_el1
    0x580001e7, -- 	ldr	x7, <.aff_mask>
    0x8a0600e7, -- 	and	x7, x7, x6
    0xf10000ff, -- 	cmp	x7, #0x0
    0x54000061, -- 	b.ne	<.secondary>  // b.any
    -- <.core0>:
    0x580001a4, -- 	ldr	x4, <.kernel_entry>
    0x14000004, -- 	b	<.boot>
    -- <.secondary>:
    0xd503205f, -- 	wfe
    0x580001c4, -- 	ldr	x4, <.spintable>
    0xb4ffffc4, -- 	cbz	x4, <.secondary>
    -- <.boot>:
    0x58000140, -- 	ldr	x0, <.dtb_ptr>
    0xaa1f03e1, -- 	mov	x1, xzr
    0xaa1f03e2, -- 	mov	x2, xzr
    0xaa1f03e3, -- 	mov	x3, xzr
    0xd61f0080, -- 	br	x4
    0x00000000, -- 	.word	0x00000000
    -- <.aff_mask>:
    0x00ffffff, -- 	.word	0x00ffffff
    0x00000000, -- 	.word	0x00000000
    -- <.kernel_entry>:
    _KERNEL64_LOAD_ADDR, -- 	.word	0x00080000
    0x00000000, -- 	.word	0x00000000
    -- <.dtb_ptr>:
    _DTB_LOAD_ADDR, -- 	.word	0x08000000
    0x00000000, -- 	.word	0x00000000
    -- <.spintable>:
    0x00000000, -- 	.word	0x00000000
}
