set(CTEST_CUSTOM_TESTS_IGNORE 
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.1/dpipe/dpipe
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.1/forkjoin/forkjoin
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.1/reset_signal_is/reset_signal_is
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.1/sc_export/sc_export
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.1/sc_report/sc_report
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.1/scx_barrier/scx_barrier
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.1/scx_mutex_w_policy/scx_mutex_w_policy
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.1/specialized_signals/specialized_signals
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.3/sc_rvd/sc_rvd
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.3/sc_ttd/sc_ttd
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.3/simple_async/simple_async
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/fft/fft_flpt/fft_flpt
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/fft/fft_fxpt/fft_fxpt
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/fir/fir
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/fir/fir_rtl
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/pipe/pipe
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/pkt_switch/pkt_switch
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/risc_cpu/risc_cpu
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/rsa/rsa
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/simple_bus/simple_bus
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/simple_fifo/simple_fifo
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/simple_perf/simple_perf
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/tlm/at_1_phase/at_1_phase
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/tlm/at_2_phase/at_2_phase
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/tlm/at_4_phase/at_4_phase
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/tlm/at_extension_optional/at_extension_optional
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/tlm/at_mixed_targets/at_mixed_targets
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/tlm/at_ooo/at_ooo
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/tlm/lt/lt
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/tlm/lt_dmi/lt_dmi
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/tlm/lt_extension_mandatory/lt_extension_mandatory
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/tlm/lt_mixed_endian/lt_mixed_endian
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/tlm/lt_temporal_decouple/lt_temporal_decouple
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.4/in_class_initialization/in_class_initialization
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.4/in_class_initialization/in_class_initialization_pimpl
@CMAKE_BINARY_NAME@/_deps/systemclanguage-src/examples/sysc/2.4/sc_optional/sc_optional_demo
)