name: macOS Builds

on: [ pull_request, push, workflow_dispatch ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-15, macOS-26 ]
        preset: [ mac, mac-debug ]

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: scripts/install_dependencies.sh

      - name: Configure
        run: >
          cmake --preset "${{ matrix.preset }}"
          -DGREENSOCS_GIT="https://github.com/quic/"
          -DLIBQEMU_TARGETS="aarch64;hexagon"

      - name: Build
        run: cmake --build --preset "${{ matrix.preset }}" --parallel $(sysctl -n hw.logicalcpu)

      - name: Test
        run: ctest --preset "${{ matrix.preset }}"
