name: Ubuntu Builds

on: [ pull_request, push, workflow_dispatch ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04 ]
        preset: [ gcc, gcc-debug, clang, clang-debug, clang-lto ]

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo scripts/install_dependencies.sh

      - name: Configure
        run: >
          cmake --preset "${{ matrix.preset }}"
          -DGREENSOCS_GIT="https://github.com/quic/"
          -DLIBQEMU_TARGETS="aarch64;hexagon"

      - name: Build
        run: cmake --build --preset "${{ matrix.preset }}" --parallel $(nproc)

      - name: Test
        run: ctest --preset "${{ matrix.preset }}"
