name: Windows Builds

on: [pull_request, push, workflow_dispatch, workflow_call]

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: ucrt64, runs-on: "windows-latest", preset: "gcc" }
          - { sys: clangarm64, runs-on: "windows-11-arm", preset: "clang" }

    name: ${{ matrix.sys }}

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          update: true

      - name: Install dependencies
        run: scripts/install_dependencies.sh

      - name: Configure
        run: >
          cmake --preset=${{ matrix.preset }}
          -DGREENSOCS_GIT="https://github.com/quic/"
          -DLIBQEMU_TARGETS="aarch64;hexagon"

      - name: Build
        run: cmake --build --preset=${{ matrix.preset }} --parallel $(nproc)

      - name: Test
        # Disable parallel test runs on GitHub runners due to resource constraints
        run: ctest --preset=${{ matrix.preset }} --parallel 1
